name: Go

on: 
  push:
    branches: [main]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module repository
        uses: actions/checkout@v3

      - name: Run migrations
        run: migrate up

      - name: Test
        run: make test